main : main.cpp shape.cpp circle.cpp rectangle.cpp rounded_rectangle.cpp parallelepiped.cpp cylinder.cpp
	g++ -o main main.cpp shape.cpp circle.cpp rectangle.cpp rounded_rectangle.cpp parallelepiped.cpp cylinder.cpp

run : main
	./main